SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO I, ONLINE_SALE S
WHERE I.USER_ID = S.USER_ID AND GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER