# BOOK(BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE)
# AUTHOR(AUTHOR_ID, AUTHOR_NAME)
# BOOK_SALES(BOOK_ID, SALES_DATE, SALES)
SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE SALES_DATE LIKE '2022-01%' AND 
    BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID AND 
    BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;